//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 08:08:09 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.usp.br/stralibam/ws/assess_eligibility_availability", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.usp.stralibam.ws.assess_eligibility_availability;
